name: Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm publish --access publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
